### ISSUE TITLE
xDiskAccessPath - UniqueId format different between server 2012 and 2016

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xStorage#104]
@PlagueHO I hope this one doesn't cause too much work. We've just deployed out first 2016 server in the lab and noticed that UniqueId has a different format between operating systems. I feel terrible because I was the one that initially suggested using UniqueId but it looks like Guid should have been used instead. I had no idea Microsoft changed the formatting between OS versions. Damn!

Have you seen this as well in your 2016 environment? The problem I face now is our CMDB is set to take in a Guid, 32 to 36 characters.

```
[LABSERVER2012]: PS C:\Users\labuser01\Documents> Get-Disk | Select-Object -Last 1 | Select-Object -Property Guid,UniqueId

Guid                                   UniqueId
----                                   --------
{3dec02ec-708e-45df-b6cc-2e644d57f035} 6000C292A946D3A9C79FDC453A6293FF
```

```
[LABSERVER2016]: PS C:\Users\labuser01\Documents> Get-Disk | Select-Object -Last 1 | Select-Object -Property Guid,UniqueId

Guid                                   UniqueId                                                                  
----                                   --------                                                                  
{f84ea0fe-3a78-4462-a1ed-9820d7965a51} SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1F2A051C&0&000300:LABSERVER2016
```

**Comment by Zuldan** [comment]
I guess one solution would be to add a 3rd DiskIdType called Guid.

**Comment by PlagueHO** [comment]
Hi @Zuldan - that is actually OK :grin: I had suspected we might need other identifier types down the track, so I did write the code with that in mind. So I'll work on it (once I've got my other PR through) and get a solution! Always happy to have improvements to make!

**Comment by Zuldan** [comment]
Thank you very much @PlagueHO

**Comment by PlagueHO** [comment]
Hi @Zuldan - I'll get onto this one this weekend and see if I can get it included in the next release of xStorage.

**Comment by Zuldan** [comment]
@PlagueHO thank you very much. Looking forward to it.

**Comment by PlagueHO** [comment]
Hi @Zuldan - I've run into a bit of a big problem with this change:

The GUID for a disk only exists once it has been initialized with a GPT partition table - which of course can't be done because the disk can't be selected/found. And also, you'd not know the GUID for the disk to load into the DSC Config.

I could still perform this change, but this would only ever work for disks that were already initialized with a GPT partition table and you'd pulled the GUID out of it. Unfortunately I nearly completed the change before figuring this problem out so I'd rather not waste the effort. :cry:

**Comment by Zuldan** [comment]
Ok now I feel really bad but if we had gone with GUID originally we would have run into the same problem. Surely Microsoft has a way to identify a disks through their entire life cycle. I'll do some digging around.

Adding GUID support is not a complete waste. I could modify our provisioning system to automatically initialize the disks before DSC runs. I'm sure others could do the same.

**Comment by Zuldan** [comment]
Ok maybe a sign of hope.

UniqueId in Get-PhysicalDisk (in 2016) appears to be in the same format as UniqueId in Get-Disk (in 2012 R2). I haven't checked to see if Get-PhysicalDisk in 2012 R2 is the same format too.

**Comment by PlagueHO** [comment]
Oh no worries - it's all good :grin:

I'm going to keep the feature in there anyway as I think it may still be useful for the reasons you've suggested. I also improved the code a little so that if there are other disk identifiers we can use then it should be easier to update in future.

You can try it out here:
https://github.com/PlagueHO/xStorage/tree/Issue-104

I've just got to fix the unit tests and I should be able to submit a PR for review.


I'll

**Comment by Zuldan** [comment]
@PlagueHO thank you very much. I'll give it a test run in the lab tomorrow.

What are your thoughts on UniqueId in Get-PhysicalDisk in 2016?

**Comment by PlagueHO** [comment]
Hi @Zuldan - I'm not sure. I used Get-PhysicalDisk and Get-Disk on one of my WS 2016 servers and both of them displayed the same uniqueId values - although the disks were returned in a different order.

So I'm not sure we can rely on this.

**Comment by Zuldan** [comment]
No worries. Thanks for the feedback :)

**Comment by Zuldan** [comment]
@PlagueHO the added GUID support worked a treat today. Thank you very much. A crate of beers to you!

**Comment by PlagueHO** [comment]
Awesome @Zuldan ! Really great to hear! Hopefully I can get someone to review the PR so it can be included in the next release. No need for the beers :grin:

**Comment by Zuldan** [comment]
I think I came across a bug today. If you change a fully configured volumes drive letter to something it shouldn't be then runs consistency check the resource says something like "creating partition on disk blah blah and assigning drive letter blah blah then fails saying not enough disk space. 2 issues from that, it shouldn't say creating partition when one exists and it's trying to do something funky with expanding the volume even though only the drive letter changed. I forgot to grab a copy of the exact wording. Doh! I'll try re-create the problem and create an issue for it. Just thought I'd let you know before hand.

**Comment by PlagueHO** [comment]
Hi @Zuldan - this is most like the same cause as this one:
https://github.com/PowerShell/xStorage/issues/103

But definitely report this if you can with logs and I'll get onto it... as soon as I can :grin:
