### ISSUE TITLE
Convert xOpticalDiskDriveLetter to SingleInstance pattern resource

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xStorage#138]
Because xOpticalDiskDriveLetter can only change the disk letter of a single optical drive in a system then it should use the SingleInstance pattern to ensure only a single resource can be used of this type per config.

**Comment by johlju** [comment]
I will review this as soon as you send in a PR (or when I wake up) :)

**Comment by PlagueHO** [comment]
Thanks @johlju - I really appreciate that. I've nearly finished it. I did a bit of a clean up on some of the style issues that I missed in the original PR (actually quite a few). But I knew you'd pick them up so better to fix them :grin:

**Comment by johlju** [comment]
Sounds great! 😆  It's morning here now, so I will review it as soon as you PR it in.

**Comment by PlagueHO** [comment]
I'm not sure this resource is correct. I've raised issues in #140

**Comment by PlagueHO** [comment]
This is no longer required.
