### ISSUE TITLE
xOpticalDiskDriveLetter missing from Master branche

### ISSUE THREAD

**Issue by erwinvandijk** [PowerShell/xStorage#143]
The DSC resource xOpticalDiskDriveLetter is missing in the Master branch. Version 3.4.0.0.

**Comment by PlagueHO** [comment]
Hi @erwinvandijk - this will be merged to master when the next release on the DSC Resource kit goes out- this is due Wednesday, 7th of Feb. In the mean time, you can use the Dev version if you wish.

**Comment by erwinvandijk** [comment]
Hi @PlagueHO , thx for the info. We already took the dev branch version for that :-).
