### ISSUE TITLE
When xDisk AllocationUnitSize is mismatched, test-targetresource should return false or throw

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xStorage#22]
I don't believe a warning alone is acceptable.  We can add another property to say it is acceptable not to change the AllocationUnitSize if the disk is already formatted, but without that described the behavior should be to get to the desired state.

**Comment by PlagueHO** [comment]
Once I've got #53 done we should be OK to work on this. The lack of tests in this module worry me a bit.

**Comment by TravisEz13** [comment]
@PlagueHO Thanks

**Comment by PlagueHO** [comment]
@TravisEz13 - I've actually included this change as part of #53. So differences to the disk that can't be changed (format, size, allocation unit size) will not trigger Set to be called.

Once #53 is completed then #50 (add a destructive switch) could be implemented to allow destructive changes to the disk.

**Comment by TravisEz13** [comment]
I think we can consider #50 separate.  Closing this issue.
