### ISSUE TITLE
xDisk fails in Test-TargetResource with error about BlockSize

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xStorage#23]
```
Cannot compare 
@{BlockSize=4096} to 0 because the objects are not the same type or the object "@{BlockSize=4096}" does not implement "IComparable"
```

**Comment by Kaidja** [comment]
Hello,

Is this bug fixed? Im using latest version on my Azure VM and I still see this issue.

Best,
Kaido

**Comment by TravisEz13** [comment]
The latest released version or the latest dev version.  The dev version is fixed.  It has not been released.

**Comment by TravisEz13** [comment]
There are instructions in install [developement builds here.](https://github.com/PowerShell/dscResources#development-builds)

**Comment by Kaidja** [comment]
Im using the production release. 

Best,
Kaido
