### ISSUE TITLE
Test-TargetRessource throws an error (comparing block sizes fails at line 225)

### ISSUE THREAD

**Issue by drmiru** [PowerShell/xStorage#28]
if($BlockSize -gt 0 -and $AllocationUnitSize -ne 0) 

should be..
if($BlockSize.**BlockSize** -gt 0 -and $AllocationUnitSize -ne 0)

**Comment by Zuldan** [comment]
Confirmed this is an issue.

Other solutions...

$BlockSize = Get-WmiObject -Query "SELECT BlockSize from Win32_Volume WHERE DriveLetter = '$($DriveLetter):'" -ErrorAction SilentlyContinue  | select <b>-ExpandProperty</b> BlockSize

or

$BlockSize = <b>(</b>Get-WmiObject -Query "SELECT BlockSize from Win32_Volume WHERE DriveLetter = '$($DriveLetter):'" -ErrorAction SilentlyContinue<b>).BlockSize</b>

**Comment by J0F3** [comment]
Is apparently already fixed in the dev branch with the Pull Request #19 from @Richiban.
So the issue should be gone with the next release to the PS gallery.
