### ISSUE TITLE
xDisk does not set disk label if disk already exists

### ISSUE THREAD

**Issue by gigi81** [PowerShell/xStorage#37]
On the xDisk dsc resource the following happens **when a disk already exists** but the disk label does not match the configured value:
- Test-DscResource return false (correct because the label does not match)
- Set-DscResource doesn't set the label (incorrect, should set the label)

**Comment by PlagueHO** [comment]
I think this one is fixed so can be closed.

**Comment by TravisEz13** [comment]
Closing based on comments
