### ISSUE TITLE
Add support for formatting Disk with ReFS in xDisk

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xStorage#54]
Any disk formatted during initialization in xDisk is formatted with NTFS.

Should add an optional parameter with FSFormat that defaults to NTFS. It could accept NTFS or ReFS.

Note: If a disk is already formatted with a different format then a warning should be shown by an error should not be thrown.

**Comment by Zuldan** [comment]
Good idea. With ReFS even better in Server 2016 I figure it's going to be used more.

**Comment by PlagueHO** [comment]
@kwirkykat  - As I'm working on this resource as part of #53, do you have any objection to me including this change in that submission?

**Comment by kwirkykat** [comment]
@PlagueHO No objections. Just make sure it's separate in the release notes please.

**Comment by PlagueHO** [comment]
@kwirkykat  - cool. Will do!

**Comment by PlagueHO** [comment]
I've finished the code change for this one in #53.

**Note:** If the disk format of the volume is different to the desired disk format a custom exception is thrown. However, it might be desirable to allow a "Destructive" change to a disk if required (e.g. to reformat the disk). This behaviour was requested in #50.

@TravisEz13, @kwirkykat  - is a "Destructive" switch something we should allow?

**Comment by TravisEz13** [comment]
I would say the property would be AllowDestructive and you only do destructive if needed.

**Comment by PlagueHO** [comment]
@TravisEz13  - sounds reasonable to me. I'll copy this comment into #50
