### ISSUE TITLE
Use a disk's unique id with the xDisk resource?

### ISSUE THREAD

**Issue by detailedschematic** [PowerShell/xStorage#55]
Can we incorporate a disk's unique id (NAA ID) into the xDisk resource?

During a SQL Server failover cluster build with SAN attached storage, I noticed that disk numbers assigned by Windows do not necessarily follow the increasing order of NAAIDs during LUN creation.

**Example:**
NAAID '100A', VolumeLabel 'Data'   -> WindowsAssignedDiskNum 0 (expected 0)
NAAID '100B', VolumeLabel 'Logs'   -> WindowsAssignedDiskNum 3 (expected 1)
NAAID '100C', VolumeLabel 'TempDB' -> WindowsAssignedDiskNum 1 (expected 2)
NAAID '100D', VolumeLabel 'Quorum' -> WindowsAssignedDiskNum 2 (expected 3)

Since I do not reliably know which disk numbers will be associated with which volumes in advance, I cannot use the xDisk resource in a configuration unless I first manually confirm the disk number to volume label (FSLabel) mappings. This interrupts the complete automation experience. 

However, the LUNs NAA ID to volume label mappings are known after creating LUNs, which is a step prior to node configuration. It would be great if the NAA ID information could be used in place of disk numbers in the xDisk resource.

**Example:**
xDisk 'DataDisk'
{
UniqueId = "100A"
DriveLetter = "G"
FSLabel = "Data"
AllocationUnitSize = 65536
}

I suppose the NAA ID to disk number resolution could be achieved outside the xDisk resource (Get-Disk | select number, uniqueid), in the DSC configuration script. But in my case, I'm using the xDisk resource inside a Chef recipe where native powershell code output isn't easily mixed in. I am still investigating my options there.

Thanks for entertaining my suggestion!

**Comment by detailedschematic** [comment]
Just wanted to note that I was able to map NAA IDs to Windows disk numbers in Chef. I used Chef's powershell_out() function to execute Powershell code inside a Chef recipe, and use the output string with some logic, to determine the disk number supplied to the xDisk DSC resource.

In that way, I was able to completely and reliably automate the LUN configuration process using DSC with Chef - awesome! Since my original issue is resolved with that workaround, I don't mind if this issue is closed.

**Comment by Zuldan** [comment]
@detailedschematic, if possible, could you kindly share with us your Chef/Powershell code so we can see the full solution?

**Comment by detailedschematic** [comment]
Sorry for the delay. I've pasted a snippet from my Chef recipe below.

A here-doc string contains powershell code:
`
naaid_to_disknum = <<-code
    $disk = Get-Disk -UniqueId #{naaid};
    return $disk.number
code
`

We call that powershell code in Chef using powershell_out() inside a dsc_resource resource. We use lazy attribute evaluation to delay until the execution phase of convergence:
`
dsc_resource "xClusterDisk" do
    resource :xClusterDisk
    property :Ensure, 'Present'
    property :Label, label
    property :Number, lazy { powershell_out(naaid_to_disknum).stdout.chop.to_s }   
end`
