### ISSUE TITLE
Mounted ISO is not available straight after mounting

### ISSUE THREAD

**Issue by gaelcolas** [PowerShell/xStorage#58]
When I have a DSC resource mounting an ISO, the mounted image is not available straight away:
```PowerShell
xMountImage MOUNT_ISO {
            Ensure = 'Present'
            ImagePath = 'C:\MY.iso'
            DriveLetter = 'S:'
            Name = 'ISO'
        }
Script TEST_ISO {
    GetScript  =  {
                return @{'result'=(Test-Path 'S:\')}
            }
            TestScript =  {
                Test-Path 'S:\'
            }
            SetScript  =  {
                $countdown = 1
                while (!(Test-Path 'S:\'))
                {
                    Write-Verbose "Waiting and Counting down $Countdown"
                    Get-PSDrive
                    Start-Sleep -Seconds 1
                    if($countdown++ -ge 5) {
                        Throw "The iso took more than 5 seconds to mount"
                    }
                }
            }
}
```
This fails, unless I refresh the PS drives by adding `$null = Get-PSDrive`

It'd be good to add this in the xMountImage Set-TargetResource scriptblock.

**Comment by kwirkykat** [comment]
@gaelcolas What happens if you add ```DependsOn = "[xMountImage]MOUNT_ISO"``` as a property in your Script resource to ensure that the xMountImage resource is run before the script resource starts? Still the same performance issue?

**Comment by PlagueHO** [comment]
There is a delay before a mounted image shows up.

We could do one of the following things:
1. Add a new resource called "xWaitForDiskImage" - this would be almost identical to "xWaitForDisk" - so wouldn't be a big difficulty implementing.

2. Add a parameter to the xMountImage to force it to "Wait" for the image to complete mounting and be available before continuing. But if we did that we'd want to implement RetryIntervalSec and RetryCount to prevent the resource from locking the LCM indefinitely on the node should the image fail to mount for some reason.

My preference is over a consistent design pattern so I'd opt for option 1. I'm happy enough to put either together at the same time as #53. I've already completely Unit tests/Integration tests, HQRM compliance for xWaitForDisk so it's a simple job to make xWaitForDiskImage.

HTH

**Comment by johlju** [comment]
I would agree to go with option 1

**Comment by mgreenegit** [comment]
That would be my feedback as well.  WaitForDisk started because of this behavior exactly concerning disks, so it would be consistent to do the same for images.  Good call.

**Comment by PlagueHO** [comment]
Ok cool. I'll get it done as part of #53. Will have that completed as soon as I get some feedback on the other suggested changes. All the unit and integration tests are complete now.

**Comment by PlagueHO** [comment]
Ok cool. I'll get it done as part of #53. Will have that completed as soon as I get some feedback on the other suggested changes. All the unit and integration tests are complete now.

**Comment by gaelcolas** [comment]
Damn, I just realized that none of my previous posts made it here from my mobile! :/

Yes @kwirkykat, same result with DependsOn.

The delay is not with mounting the iso as you may have with disks, but with refreshing the PS drives. In my example I wait 5 seconds, much more than necessary for the iso to be mounted.
You can see that when running and watching the GUI, ISO is mounted straight away, but PS drives not refreshed in the LCM PS session even after 5 seconds.
 
The one liner to refresh works without any delay (btw, it’s a known trick with PS Drives), and without adding complexity.
 
Although xWaitForDiskImage might be needed for other scenarios, we should still add this refresh.

What do you think?

**Comment by PlagueHO** [comment]
Just working on this: I'm thinking that it should be "xWaitForDrive" rather than "xWaitForDiskImage". This is because it is actually going to wait for the drive (using PSDrive) as @gaelcolas suggests. Therefore it could be used in other scenarios:

For example it could actually work for a Windows Cluster server to trigger some action when a disk connects after a failover occurs (e.g. the DSC configs that are after this one will only occur once a cluster disk first connects).

Is this name going to be OK? I realize it is quite close to the existing "xWaitForDisk" one.

**Comment by PlagueHO** [comment]
I've completed this resource (with unit/integration tests) and it should be up to HQRM standards. I'll commit it once I have feedback on the name "xWaitForDrive"- it'll go in as part of #53 - which is currently being blocked by #38, #57 and #56.

**Comment by Zuldan** [comment]
Great work Daniel. Can't wait to see what a HQRM (that's been created from scratch) looks like. 

With regards to the name. To list disks you use Get-Disk (hence xWaitForDisk). To get the drives on those disks you use Get-Volume. So technically the resource should be (at least I think) xWaitForVolume. This would also avoid confusion with similar names (xWaitForDisk and xWaitForDrive). What are your thoughts?

**Comment by PlagueHO** [comment]
Thanks @Zuldan! This won't really have been created from scratch of course though - [this resource](https://github.com/PowerShell/SystemLocaleDsc) was created from scratch as HQRM. If I can bring xStorage up to HQRM standards though then hopefully it can be relabeled as an HQRM resource (StorageDsc).

I like your idea of xWaitForVolume - I think that is a much cleaner name. I'll rename it.
