### ISSUE TITLE
Error in Sample_InitializeDataDisk

### ISSUE THREAD

**Issue by spaelling** [PowerShell/xStorage#68]
`Count` is not a valid member. It should be `RetryCount`.

[Sample_InitializeDataDisk.ps1](https://github.com/PowerShell/xStorage/blob/dev/Examples/Sample_InitializeDataDisk.ps1)

**Comment by PlagueHO** [comment]
@spaelling - good catch! Feel free to submit a PR if you want or I'll get onto it this weekend. Thanks for submitting this.
